### ISSUE TITLE
Game lädt nicht mehr

### ISSUE THREAD

**Issue by TimRepke** [TimRepke/registration-system#43]
Der Mindblow-Modus geht nicht mehr in Chrome:
https://fsfahrt.fachschaft.informatik.hu-berlin.de/view/signups/game1/test.html

Firefox geht.

Fehler tritt hier auf:

```
function getTranslation(svg, node) {
   var matrix = svg.getTransformToElement(node);
   return [matrix.e, matrix.f];
}
```

> glaub das getTransformToElement is einfach nicht 'stable'
> aber das beste was man bekommen konnte
> https://github.com/cpettitt/dagre-d3/issues/202

> As suggested by the JointJS team this function can be poly-filled where it is required. We are working around this locally with a polyfil for now, but it clearly would be better for dagre-d3 to centralise a fix (polyfil or otherwise) so that everyone using Chrome 48 can benefit.

**Comment by 0x17de** [comment]
Issue fixed with polyfill from http://jointjs.com/blog/get-transform-to-element-polyfill.html
